PAYLAPMEXT 207, 209, 210
PaylinePaymentMethod/payment-method-sandbox pull request #3
Opened 2020-07-06 14:56 UTC by martin-grescu

PAYLAPMEXT-207:  Modification de la gestion des exceptions
PAYLAPMEXT-209: Traitement des cas 30002 & 30003
PAYLAPMEXT-210: Délai d'attente  + ajout de tests unitaire

2020-08-04 09:22 UTC, martin-grescu commented
![image](https://user-images.githubusercontent.com/55979277/89277128-b457e200-d644-11ea-86ad-1a5bb9ef910a.png)

2020-08-04 09:29 UTC, martin-grescu commented
Pas de changement des Partner_conf

2020-10-12 15:06 UTC, pesublet requested changes

2020-10-12 15:06 UTC, pesublet commented on build.gradle
> +    paymentMethodApiVersion = '1.7'
Tu peux monter en 1.9 si tu veux la dernière

2020-10-12 15:06 UTC, pesublet commented on src/main/java/com/payline/payment/sandbox/exception/PluginException.java
> +    public static String runtimeErrorCode( RuntimeException e ){
ça peut aller dans un service ou Utils mais pas dans une classe d'Exception directement

2020-10-12 15:06 UTC, pesublet commented on src/test/java/com/payline/payment/sandbox/exception/PluginExceptionTest.java
> +        assertNotNull( exception.getMessage() );
Qu'est ce qui me garanti qu'il n'y a pas "TOTO" ou "TATA" dans le message ? ou même pire, une chaine vide !  
Il faut tester le contenu

2020-10-12 15:06 UTC, pesublet commented on src/test/java/com/payline/payment/sandbox/exception/PluginExceptionTest.java
> +    @MethodSource("constructorsTestSet")
Tu prends le problème à l'envers je pense, tu devrais passer ici les arguments des PluginException de `constructorsTestSet()` puis instancier tes exceptions dans la méthode de test. Tu peux ensuite facilement tester ton exception pour vérifier qu'elle est bien construite

2020-10-12 15:06 UTC, pesublet commented on src/test/java/com/payline/payment/sandbox/exception/PluginExceptionTest.java
> +                Arguments.of( new PluginException(LONG_MESSAGE), FailureCause.COMMUNICATION_ERROR, CAUSE )
ajouter un message court pour vérifier qu'il n'est pas tronqué

2020-10-12 15:06 UTC, pesublet commented on src/test/java/com/payline/payment/sandbox/exception/PluginExceptionTest.java
> +        this.exception = new PluginException(LONG_MESSAGE, FailureCause.COMMUNICATION_ERROR, CAUSE);
Je suis pas fan, tu vois plus ce que tu testes dans `toPaymentResponseFailure()`  
Pour moi il faut mettre cette ligne dans chaque test, même si ça prend un peu plus de place cela améliore la lisibilité du test.

2020-10-12 15:06 UTC, pesublet commented on src/test/java/com/payline/payment/sandbox/exception/PluginExceptionTest.java
> +        assertNotNull( prf.getErrorCode() );
Vérifier le contenu en plus de la nullité

2020-10-12 15:06 UTC, pesublet commented on src/test/java/com/payline/payment/sandbox/exception/PluginExceptionTest.java
> +        assertNotNull( pfcrf.getErrorCode() );
Vérifier le contenu en plus de la nullité

2020-10-12 15:06 UTC, pesublet commented on src/test/java/com/payline/payment/sandbox/exception/PluginExceptionTest.java
> +        assertNotNull( rrf.getErrorCode() );
Vérifier le contenu en plus de la nullité

2020-10-12 15:06 UTC, pesublet commented on src/test/java/com/payline/payment/sandbox/exception/PluginExceptionTest.java
> +        catch( RuntimeException e ){
Pourquoi ne pas instancier une RuntimeException si tu veux tester ta méthode ?

2020-10-12 15:06 UTC, pesublet commented on src/test/java/com/payline/payment/sandbox/service/impl/ConfigurationServiceImplTest.java
> +        assertNotNull(name);
C'est quoi son p'tit nom ?

2020-10-12 15:10 UTC, pesublet commented on build.gradle
> +    paymentMethodApiVersion = '1.7'
Je viens de voir que la prochaine PR montait à cette version donc pas besoin de le faire ici

2020-10-29 14:59 UTC, JanFLORENT commented on src/main/java/com/payline/payment/sandbox/exception/PluginException.java
> +    public static String runtimeErrorCode( RuntimeException e ){
inutilisé, j'enlève

2020-10-29 15:24 UTC, JanFLORENT commented on src/test/java/com/payline/payment/sandbox/exception/PluginExceptionTest.java
> +        assertNotNull( exception.getMessage() );
fait

2020-10-29 16:05 UTC, JanFLORENT commented on src/test/java/com/payline/payment/sandbox/exception/PluginExceptionTest.java
> +    @MethodSource("constructorsTestSet")
ce test etait foireux je l'ai repris, avec cette logique

2020-10-29 16:06 UTC, JanFLORENT commented on src/test/java/com/payline/payment/sandbox/exception/PluginExceptionTest.java
> +                Arguments.of( new PluginException(LONG_MESSAGE), FailureCause.COMMUNICATION_ERROR, CAUSE )
fait

2020-10-29 16:10 UTC, JanFLORENT commented on src/test/java/com/payline/payment/sandbox/exception/PluginExceptionTest.java
> +        this.exception = new PluginException(LONG_MESSAGE, FailureCause.COMMUNICATION_ERROR, CAUSE);
fait

2020-10-29 16:13 UTC, JanFLORENT commented on src/test/java/com/payline/payment/sandbox/exception/PluginExceptionTest.java
> +        assertNotNull( prf.getErrorCode() );
fait

2020-10-29 16:13 UTC, JanFLORENT commented on src/test/java/com/payline/payment/sandbox/exception/PluginExceptionTest.java
> +        assertNotNull( pfcrf.getErrorCode() );
fait

2020-10-29 16:13 UTC, JanFLORENT commented on src/test/java/com/payline/payment/sandbox/exception/PluginExceptionTest.java
> +        assertNotNull( rrf.getErrorCode() );
fait

2020-10-29 16:14 UTC, JanFLORENT commented on src/test/java/com/payline/payment/sandbox/exception/PluginExceptionTest.java
> +        catch( RuntimeException e ){
test d'une methode inutilisé... j'ai viré

2020-10-29 16:16 UTC, JanFLORENT commented on src/test/java/com/payline/payment/sandbox/service/impl/ConfigurationServiceImplTest.java
> +        assertNotNull(name);
fait

2021-05-07 13:41 UTC, pesublet commented
doublon https://github.com/PaylinePaymentMethod/payment-method-sandbox/pull/4

2021-05-07 13:42 UTC, closed without merging