Paylapmext 208
PaylinePaymentMethod/payment-method-sandbox pull request #4
Opened 2020-10-06 09:55 UTC by JanFLORENT

Accepter la PR des tickets 207, 209 & 210 avant

2020-10-12 15:26 UTC, pesublet requested changes

2020-10-12 15:26 UTC, pesublet commented on src/main/java/com/payline/payment/sandbox/service/impl/PaymentFormConfigurationServiceImpl.java
> +        int height = 58;
traditionnellement on le met dans `src/main/resources/config.properties`

2020-10-12 15:26 UTC, pesublet commented on src/test/java/com/payline/payment/sandbox/service/impl/PaymentFormConfigurationServiceImplTest.java
> +        assertEquals(PaymentFormLogoResponseLink.class, response.getClass());
Ce qui est testé n'est pas ce qui est intéressant ici, il me semble que c'est le log qui nous intéresse. Il y a des moyens de tester qu'un log est envoyé, je te laisse regarder et on en rediscute si c'est trop galère

2020-10-12 15:26 UTC, pesublet commented on src/test/java/com/payline/payment/sandbox/service/impl/PaymentFormConfigurationServiceImplTest.java
> +        assertEquals(PaymentFormLogoResponseLink.class, response.getClass());
idem

2020-10-12 15:26 UTC, pesublet commented on src/test/java/com/payline/payment/sandbox/service/impl/PaymentFormConfigurationServiceImplTest.java
> +        assertEquals(PaymentFormLogoResponseLink.class, response.getClass());
idem, je te laisse vérifier pour les autres cas de test

2020-10-12 15:26 UTC, pesublet commented on src/main/java/com/payline/payment/sandbox/service/impl/PaymentFormConfigurationServiceImpl.java
> +                .withHeight(58)
Tu peux factoriser les dimensions du logo

2020-10-12 15:26 UTC, pesublet commented
Je veux bien une petite capture d'écran sonar aussi :)

2020-10-30 10:06 UTC, JanFLORENT commented on src/main/java/com/payline/payment/sandbox/service/impl/PaymentFormConfigurationServiceImpl.java
> +                .withHeight(58)
fait

2020-10-30 15:34 UTC, JanFLORENT commented on src/test/java/com/payline/payment/sandbox/service/impl/PaymentFormConfigurationServiceImplTest.java
> +        assertEquals(PaymentFormLogoResponseLink.class, response.getClass());
fait

2020-10-30 15:34 UTC, JanFLORENT commented on src/test/java/com/payline/payment/sandbox/service/impl/PaymentFormConfigurationServiceImplTest.java
> +        assertEquals(PaymentFormLogoResponseLink.class, response.getClass());
fait

2020-10-30 16:40 UTC, JanFLORENT commented on src/test/java/com/payline/payment/sandbox/service/impl/PaymentFormConfigurationServiceImplTest.java
> +        assertEquals(PaymentFormLogoResponseLink.class, response.getClass());
fait

2020-10-30 16:46 UTC, JanFLORENT commented on src/main/java/com/payline/payment/sandbox/service/impl/PaymentFormConfigurationServiceImpl.java
> +        int height = 58;
Vu avec P.E. on laisse en dur dans le code pour ne pas ajouter des service de gestions des configs

2020-11-05 13:43 UTC, JanFLORENT commented
![image](https://user-images.githubusercontent.com/41673610/98248215-eabf3900-1f74-11eb-825b-da440c28f621.png)

il manque la couvertuire par Sonar mais voici déja ca :) 
IntelliJ me dit 77%

2021-05-07 13:38 UTC, merged